name: lawyer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - flask=3.1.2
  - pandas=2.3.3
  - numpy=2.1.2
  - python-dateutil=2.9.0.post0
  - pytz=2025.2
  - tzdata=2025.2
  - firebase-admin=6.5.0
  - scikit-learn=1.5.2
  - requests=2.32.5
  - regex=2025.9.18
  - tqdm=4.67.1
  - pyyaml=6.0.3
  - psutil=7.1.0
  - rich=14.1.0
  - colorama=0.4.6
  - pip
  - pip:
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torchaudio==2.5.1+cu121
      - typing-extensions==4.12.2
      - sympy==1.13.1
      - filelock==3.13.1
      - jinja2==3.1.4
      - networkx==3.3
      - fsspec==2024.6.1
      - transformers==4.46.2
      - peft==0.13.2
      - accelerate==1.1.1
      - trl==0.12.1
      - bitsandbytes==0.45.2
      - datasets==3.1.0
      - huggingface-hub==0.26.2
      - safetensors==0.4.5
      - pyarrow==21.0.0
      - dill==0.3.8
      - xxhash==3.5.0
      - multiprocess==0.70.16
      - tensorflow==2.17.0
      - tensorflow-hub==0.16.1
